In [1]:
# PREPROCESSING

# You get some data and the data is NOT perfect to be used right away with you model
# So you wanna train...
# let's say a K neighbors classifier on your data, but the data is NOT perfect
# Some of the features mmoght not even be numerical. Some of the features might not be scaled yet.
# this is important for a distance-based classification algorithm

# So you need to pre-processing the data. you need to some stuff with the data before it can be used
# for training and evaluating the model

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# It basically scales the data to a specific format.

In [2]:
X, y = load_iris(return_X_y=True)
# To make all features equally important, what we do is we scale them down to the same variance.
# So the unit variance essentially, and we can do it different ways.

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [4]:
# we gonna do a fit transform
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [5]:
import numpy as np

(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)
# otherwise we're taking the mean across all these values here

array([[ 1.5923883 ,  0.27108173,  1.2356165 ,  0.77325495],
       [ 0.75006703, -0.19362981,  0.95784584,  0.77325495],
       [ 0.62973542, -0.42598557,  0.29119625,  0.12617968],
       [ 1.11106186, -0.65834134,  0.56896691,  0.25559473],
       [-0.9345755 ,  1.66521633, -1.26431947, -1.16797086],
       [ 1.83305152, -0.65834134,  1.29117063,  0.90267   ],
       [-1.65656516, -1.82012017, -1.37542773, -1.16797086],
       [-1.05490711, -1.82012017, -0.26434508, -0.26206548],
       [ 0.75006703, -0.19362981,  0.79118344,  1.03208506],
       [-1.05490711,  0.73579326, -1.26431947, -1.29738592],
       [-1.29557033, -0.19362981, -1.3198736 , -1.16797086],
       [ 0.50940381, -1.82012017,  0.34675038,  0.12617968],
       [-1.53623355,  1.20050479, -1.54209013, -1.29738592],
       [ 2.19404635,  1.66521633,  1.62449543,  1.29091517],
       [ 1.23139347,  0.27108173,  1.0689541 ,  1.42033022],
       [ 0.75006703, -0.19362981,  1.12450824,  1.29091517],
       [ 0.14840899, -2.

In [6]:
X_train_scaled

array([[ 1.5923883 ,  0.27108173,  1.2356165 ,  0.77325495],
       [ 0.75006703, -0.19362981,  0.95784584,  0.77325495],
       [ 0.62973542, -0.42598557,  0.29119625,  0.12617968],
       [ 1.11106186, -0.65834134,  0.56896691,  0.25559473],
       [-0.9345755 ,  1.66521633, -1.26431947, -1.16797086],
       [ 1.83305152, -0.65834134,  1.29117063,  0.90267   ],
       [-1.65656516, -1.82012017, -1.37542773, -1.16797086],
       [-1.05490711, -1.82012017, -0.26434508, -0.26206548],
       [ 0.75006703, -0.19362981,  0.79118344,  1.03208506],
       [-1.05490711,  0.73579326, -1.26431947, -1.29738592],
       [-1.29557033, -0.19362981, -1.3198736 , -1.16797086],
       [ 0.50940381, -1.82012017,  0.34675038,  0.12617968],
       [-1.53623355,  1.20050479, -1.54209013, -1.29738592],
       [ 2.19404635,  1.66521633,  1.62449543,  1.29091517],
       [ 1.23139347,  0.27108173,  1.0689541 ,  1.42033022],
       [ 0.75006703, -0.19362981,  1.12450824,  1.29091517],
       [ 0.14840899, -2.

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_test_scaled

array([[ 0.19444444,  0.59090909,  0.05084746,  0.08333333],
       [ 0.66666667,  0.40909091,  0.77966102,  0.95833333],
       [ 0.19444444,  0.59090909,  0.10169492,  0.20833333],
       [ 0.33333333,  0.04545455,  0.50847458,  0.5       ],
       [ 0.52777778,  0.27272727,  0.6440678 ,  0.70833333],
       [ 0.75      ,  0.45454545,  0.62711864,  0.54166667],
       [ 0.25      ,  0.59090909,  0.08474576,  0.04166667],
       [ 0.36111111,  0.36363636,  0.59322034,  0.58333333],
       [ 0.22222222,  0.54545455,  0.08474576,  0.04166667],
       [ 0.44444444,  0.36363636,  0.54237288,  0.58333333],
       [ 0.19444444, -0.09090909,  0.42372881,  0.375     ],
       [ 0.58333333,  0.22727273,  0.72881356,  0.75      ],
       [ 0.25      ,  0.86363636,  0.08474576,  0.        ],
       [ 0.58333333,  0.45454545,  0.72881356,  0.91666667],
       [ 0.33333333,  0.09090909,  0.45762712,  0.375     ],
       [ 0.63888889,  0.31818182,  0.61016949,  0.5       ],
       [ 0.58333333,  0.

In [8]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)

array([[0.80555556, 0.45454545, 0.84745763, 0.70833333],
       [0.61111111, 0.36363636, 0.76271186, 0.70833333],
       [0.58333333, 0.31818182, 0.55932203, 0.5       ],
       [0.69444444, 0.27272727, 0.6440678 , 0.54166667],
       [0.22222222, 0.72727273, 0.08474576, 0.08333333],
       [0.86111111, 0.27272727, 0.86440678, 0.75      ],
       [0.05555556, 0.04545455, 0.05084746, 0.08333333],
       [0.19444444, 0.04545455, 0.38983051, 0.375     ],
       [0.61111111, 0.36363636, 0.71186441, 0.79166667],
       [0.19444444, 0.54545455, 0.08474576, 0.04166667],
       [0.13888889, 0.36363636, 0.06779661, 0.08333333],
       [0.55555556, 0.04545455, 0.57627119, 0.5       ],
       [0.08333333, 0.63636364, 0.        , 0.04166667],
       [0.94444444, 0.72727273, 0.96610169, 0.875     ],
       [0.72222222, 0.45454545, 0.79661017, 0.91666667],
       [0.61111111, 0.36363636, 0.81355932, 0.875     ],
       [0.47222222, 0.        , 0.50847458, 0.375     ],
       [0.55555556, 0.31818182,